import { Feather } from "@expo/vector-icons";
import { LinearGradient } from "expo-linear-gradient";
import React, { useEffect, useState, useSyncExternalStore } from "react";
import { LayoutChangeEvent, Pressable, StyleSheet, Text, View, useWindowDimensions } from "react-native";
import { PlayerChrome as PlayerChromeV2, playerCodecLabel } from "./PlayerChromeV2";
import { getPlayerRuntimeInfoSnapshot, subscribePlayerRuntimeInfo } from "@/lib/playerRuntimeInfo";
import type { PlayerFitMode } from "./VlcPlaybackSurface";

export type { PlayerPanel, PlayerSelectableItem, PlayerMediaKind, PlayerDownloadState } from "./PlayerChromeV2";
export { playerCodecLabel };

const initializedPlayers = new WeakSet<Function>();
type FeatherName = React.ComponentProps<typeof Feather>["name"];
type Props = React.ComponentProps<typeof PlayerChromeV2> & { resolution?: string; fps?: number };
type Action = { key: string; label: string; icon?: FeatherName; glyph?: string; badge?: string; active?: boolean; accent?: boolean; disabled?: boolean; onPress: () => void };

const fitLabel = (m: PlayerFitMode) => m === "full" ? "FULL" : m === "original" ? "ORIG" : m === "16:9" ? "16:9" : m === "4:3" ? "4:3" : "FIT";
const formatTime = (s: number) => { if (!Number.isFinite(s) || s < 0) return "0:00"; const v=Math.floor(s),h=Math.floor(v/3600),m=Math.floor((v%3600)/60),x=v%60; return h?`${h}:${String(m).padStart(2,"0")}:${String(x).padStart(2,"0")}`:`${m}:${String(x).padStart(2,"0")}`; };
const formatFps = (fps: number) => Math.abs(fps-Math.round(fps)) < .015 ? String(Math.round(fps)) : fps.toFixed(2).replace(/0+$/,"" ).replace(/\.$/,"");

export function PlayerChrome(props: Props) {
  const { width, height } = useWindowDimensions();
  const portrait = height > width;
  const [seekWidth, setSeekWidth] = useState(1);
  const [secondary, setSecondary] = useState(false);
  const runtime = useSyncExternalStore(subscribePlayerRuntimeInfo, getPlayerRuntimeInfoSnapshot, getPlayerRuntimeInfoSnapshot);
  const { resolution: resolutionOverride, fps: fpsOverride, ...chrome } = props;

  useEffect(() => { const cycle=props.onCycleFit as unknown as Function; if (initializedPlayers.has(cycle)) return; initializedPlayers.add(cycle); if (props.fitMode === "fit") { props.onCycleFit(); props.onCycleFit(); } }, [props.fitMode, props.onCycleFit]);
  useEffect(() => { if (!chrome.controlsVisible || chrome.panel || !portrait) setSecondary(false); }, [chrome.controlsVisible, chrome.panel, portrait]);

  const resolution = resolutionOverride ?? runtime.resolution;
  const fps = fpsOverride ?? runtime.fps;
  const tech = resolution ? `${resolution}${fps ? ` · ${formatFps(fps)} FPS` : ""}` : fps ? `${formatFps(fps)} FPS` : undefined;
  const progress = chrome.duration > 0 ? Math.max(0, Math.min(1, chrome.position/chrome.duration)) : 0;
  const primary: Action[] = [
    ...(chrome.selectableItems.length ? [{ key:"list", label:chrome.mediaKind === "live" ? "Kanallar" : "Liste", icon:"list" as FeatherName, active:chrome.panel === "content", onPress:()=>chrome.onTogglePanel("content") }] : []),
    { key:"fit", label:"Ekran", icon:"maximize-2", badge:fitLabel(chrome.fitMode), accent:true, onPress:chrome.onCycleFit },
    ...(chrome.pipSupported ? [{ key:"pip", label:"PiP", glyph:"PiP", onPress:chrome.onEnterPip }] : []),
    { key:"cc", label:"Altyazı", glyph:"CC", active:chrome.panel === "subtitles", onPress:()=>chrome.onTogglePanel("subtitles") },
    { key:"more", label:"Diğer", icon:"more-horizontal", onPress:()=>setSecondary(true) },
  ];
  const secondaryActions: Action[] = [
    { key:"back", label:"Ana", icon:"chevron-left", onPress:()=>setSecondary(false) },
    { key:"rotate", label:"Döndür", icon:"rotate-cw", onPress:chrome.onRotate },
    { key:"audio", label:"Ses", icon:"volume-2", active:chrome.panel === "audio", onPress:()=>chrome.onTogglePanel("audio") },
    { key:"codec", label:"Codec", icon:"cpu", badge:playerCodecLabel(chrome.codecMode), accent:true, active:chrome.panel === "codec", onPress:()=>chrome.onTogglePanel("codec") },
    ...(chrome.allowDownload ? [{ key:"download", label:chrome.downloadState === "done" ? "İndirildi" : "İndir", icon:(chrome.downloadState === "done" ? "check-circle" : chrome.downloadState === "error" ? "alert-circle" : "download") as FeatherName, active:chrome.downloadState === "done", onPress:chrome.onDownload }] : []),
  ];

  return <>
    <PlayerChromeV2 {...chrome} controlsVisible={false} infoVisible={false} />
    {(chrome.controlsVisible || chrome.infoVisible) ? <><LinearGradient pointerEvents="none" colors={["rgba(0,0,0,.62)","rgba(0,0,0,.14)","rgba(0,0,0,0)"]} style={styles.topShade}/><LinearGradient pointerEvents="none" colors={["rgba(0,0,0,0)","rgba(0,0,0,.14)","rgba(0,0,0,.68)"]} style={styles.bottomShade}/></> : null}
    {chrome.infoVisible ? <Info portrait={portrait} title={chrome.title} meta={chrome.meta} live={chrome.mediaKind === "live"} tech={tech}/> : null}
    {chrome.controlsVisible && chrome.canExit ? <Pressable accessibilityRole="button" accessibilityLabel="Oynatıcıdan çık" onPress={chrome.onExit} style={({pressed})=>[styles.back,portrait?styles.backP:styles.backL,pressed&&styles.pressed]} hitSlop={10}><Feather name="arrow-left" size={portrait?24:27} color="#fff"/></Pressable> : null}
    {chrome.controlsVisible && !chrome.panel ? <View style={[styles.center,portrait?styles.centerP:styles.centerL]} pointerEvents="box-none">
      {chrome.mediaKind !== "live" ? <Round compact={portrait} icon="rotate-ccw" badge="10" label="10 saniye geri" onPress={()=>chrome.onSeekBy(-10)}/> : chrome.canNavigate ? <Round compact={portrait} icon="skip-back" label="Önceki kanal" disabled={chrome.currentIndex<=0} onPress={()=>chrome.onMoveRelative(-1)}/> : null}
      <Pressable accessibilityRole="button" accessibilityLabel={chrome.paused?"Oynat":"Duraklat"} onPress={chrome.onTogglePause} style={({pressed})=>[styles.play,portrait&&styles.playP,pressed&&styles.playPressed]} hitSlop={10}><LinearGradient colors={["#c7fbff","#22d3ee","#0ea5e9"]} style={styles.playInner}><Feather name={chrome.paused?"play":"pause"} size={portrait?30:36} color="#02131b"/></LinearGradient></Pressable>
      {chrome.mediaKind !== "live" ? <Round compact={portrait} icon="rotate-cw" badge="15" label="15 saniye ileri" onPress={()=>chrome.onSeekBy(15)}/> : chrome.canNavigate ? <Round compact={portrait} icon="skip-forward" label="Sonraki kanal" disabled={chrome.currentIndex>=chrome.selectableItems.length-1} onPress={()=>chrome.onMoveRelative(1)}/> : null}
    </View> : null}
    {chrome.controlsVisible ? <View style={[styles.bottom,portrait?styles.bottomP:styles.bottomL]} pointerEvents="box-none">
      {chrome.mediaKind !== "live" && !chrome.panel ? <View style={styles.seekRow}><Text style={styles.time}>{formatTime(chrome.position)}</Text><Pressable onLayout={(e:LayoutChangeEvent)=>setSeekWidth(Math.max(1,e.nativeEvent.layout.width))} onPress={(e)=>chrome.onSeekRatio(Math.max(0,Math.min(1,e.nativeEvent.locationX/seekWidth)))} style={styles.seekTouch} hitSlop={{top:12,bottom:12,left:0,right:0}}><View style={styles.seekTrack}><LinearGradient colors={["#67e8f9","#22d3ee","#0284c7"]} style={[styles.seekFill,{width:`${progress*100}%`}]}/><View style={[styles.seekThumb,{left:`${progress*100}%`}]}/></View></Pressable><Text style={[styles.time,styles.timeR]}>{formatTime(chrome.duration)}</Text></View> : null}
      {portrait ? <Tray portrait><View style={styles.rowP}>{(secondary?secondaryActions:primary).map(a=><ActionButton key={a.key} action={a} portrait/>)}</View><View style={styles.pages}><View style={[styles.pageDot,!secondary&&styles.pageDotA]}/><View style={[styles.pageDot,secondary&&styles.pageDotA]}/></View></Tray> : <Tray><View style={styles.rowL}>
        {chrome.selectableItems.length ? <ActionButton action={{key:"list",label:chrome.mediaKind === "live"?"Kanallar":"Liste",icon:"list",active:chrome.panel === "content",onPress:()=>chrome.onTogglePanel("content")}}/> : null}
        <ActionButton action={{key:"fit",label:"Ekran",icon:"maximize-2",badge:fitLabel(chrome.fitMode),accent:true,onPress:chrome.onCycleFit}}/><ActionButton action={{key:"rotate",label:"Döndür",icon:"rotate-cw",onPress:chrome.onRotate}}/>
        {chrome.pipSupported ? <ActionButton action={{key:"pip",label:"PiP",glyph:"PiP",onPress:chrome.onEnterPip}}/> : null}<View style={styles.divider}/>
        <ActionButton action={{key:"cc",label:"Altyazı",glyph:"CC",active:chrome.panel === "subtitles",onPress:()=>chrome.onTogglePanel("subtitles")}}/><ActionButton action={{key:"audio",label:"Ses",icon:"volume-2",active:chrome.panel === "audio",onPress:()=>chrome.onTogglePanel("audio")}}/><ActionButton action={{key:"codec",label:"Codec",icon:"cpu",badge:playerCodecLabel(chrome.codecMode),accent:true,active:chrome.panel === "codec",onPress:()=>chrome.onTogglePanel("codec")}}/>
        {chrome.allowDownload ? <ActionButton action={{key:"download",label:chrome.downloadState === "done"?"İndirildi":"İndir",icon:chrome.downloadState === "done"?"check-circle":chrome.downloadState === "error"?"alert-circle":"download",active:chrome.downloadState === "done",onPress:chrome.onDownload}}/> : null}
      </View></Tray>}
    </View> : null}
  </>;
}

function Info({portrait,title,meta,live,tech}:{portrait:boolean;title:string;meta?:string;live:boolean;tech?:string}) { return <View pointerEvents="none" style={[styles.info,portrait?styles.infoP:styles.infoL]}><LinearGradient colors={["rgba(5,14,23,.96)","rgba(5,12,20,.88)"]} style={StyleSheet.absoluteFillObject}/><View style={styles.rail}/><View style={styles.infoCopy}><View style={styles.titleRow}>{live?<View style={[styles.live,portrait&&styles.liveP]}><View style={styles.dot}/><Text style={styles.liveText}>CANLI</Text></View>:null}<Text numberOfLines={1} ellipsizeMode="tail" style={[styles.title,portrait&&styles.titleP]}>{title}</Text></View><View style={styles.metaRow}>{meta?<Text numberOfLines={1} style={styles.meta}>{meta}</Text>:null}<View style={[styles.tech,!tech&&styles.techMuted]}><Feather name="monitor" size={11} color={tech?"#67e8f9":"#64748b"}/><Text numberOfLines={1} style={tech?styles.techText:styles.techMutedText}>{tech??"Akış bilgisi bekleniyor"}</Text></View></View></View></View>; }
function Round({icon,badge,compact,disabled,label,onPress}:{icon:FeatherName;badge?:string;compact?:boolean;disabled?:boolean;label:string;onPress:()=>void}) { return <Pressable accessibilityRole="button" accessibilityLabel={label} disabled={disabled} onPress={onPress} style={({pressed})=>[styles.round,compact&&styles.roundP,disabled&&styles.disabled,pressed&&!disabled&&styles.pressed]}><Feather name={icon} size={compact?24:29} color="#fff"/>{badge?<Text style={styles.roundBadge}>{badge}</Text>:null}</Pressable>; }
function Tray({portrait=false,children}:{portrait?:boolean;children:React.ReactNode}) { return <View style={[styles.tray,portrait?styles.trayP:styles.trayL]}><LinearGradient pointerEvents="none" colors={["rgba(13,23,34,.97)","rgba(4,9,15,.97)"]} style={StyleSheet.absoluteFillObject}/><View style={styles.glow}/>{children}</View>; }
function ActionButton({action,portrait=false}:{action:Action;portrait?:boolean}) { const hi=action.active||action.accent; return <Pressable accessibilityRole="button" accessibilityLabel={action.label} disabled={action.disabled} onPress={action.onPress} style={({pressed})=>[styles.action,portrait&&styles.actionP,hi&&styles.actionHi,action.active&&styles.actionActive,action.disabled&&styles.disabled,pressed&&!action.disabled&&styles.actionPressed]}><View style={styles.iconBox}>{action.icon?<Feather name={action.icon} size={portrait?21:22} color={hi?"#8beeff":"#fff"}/>:<Text style={[styles.glyph,hi&&styles.glyphA]}>{action.glyph}</Text>}{action.badge?<View style={styles.badge}><Text numberOfLines={1} style={styles.badgeText}>{action.badge}</Text></View>:null}</View><Text numberOfLines={1} style={[styles.actionLabel,action.active&&styles.actionLabelA]}>{action.label}</Text></Pressable>; }

const styles=StyleSheet.create({
  topShade:{position:"absolute",zIndex:40,top:0,left:0,right:0,height:128},bottomShade:{position:"absolute",zIndex:40,bottom:0,left:0,right:0,height:165},
  info:{position:"absolute",zIndex:52,top:14,overflow:"hidden",borderWidth:1,borderColor:"rgba(71,101,124,.44)",backgroundColor:"rgba(5,12,20,.9)",elevation:8,flexDirection:"row",alignItems:"center"},infoL:{left:92,right:18,minHeight:58,borderRadius:18,paddingLeft:17,paddingRight:13},infoP:{left:70,right:12,minHeight:62,borderRadius:17,paddingLeft:13,paddingRight:10},rail:{position:"absolute",left:0,top:0,bottom:0,width:4,backgroundColor:"#22d3ee"},infoCopy:{flex:1,minWidth:0,paddingVertical:8},titleRow:{flexDirection:"row",alignItems:"center",gap:8,minWidth:0},live:{height:23,paddingHorizontal:8,borderRadius:12,flexDirection:"row",alignItems:"center",gap:5,borderWidth:1,borderColor:"rgba(34,211,238,.38)",backgroundColor:"rgba(8,145,178,.16)"},liveP:{height:21,paddingHorizontal:7},dot:{width:6,height:6,borderRadius:3,backgroundColor:"#22d3ee"},liveText:{color:"#8beeff",fontSize:10,fontWeight:"900"},title:{flex:1,minWidth:0,color:"#f8fafc",fontSize:18,fontWeight:"900"},titleP:{fontSize:15},metaRow:{marginTop:5,flexDirection:"row",alignItems:"center",gap:8,minWidth:0},meta:{flexShrink:1,color:"#94a3b8",fontSize:11,fontWeight:"700"},tech:{flexShrink:0,minHeight:22,maxWidth:"66%",paddingHorizontal:7,borderRadius:11,flexDirection:"row",alignItems:"center",gap:5,borderWidth:1,borderColor:"rgba(103,232,249,.3)",backgroundColor:"rgba(8,145,178,.12)"},techMuted:{borderColor:"transparent",backgroundColor:"transparent"},techText:{color:"#dffaff",fontSize:10,fontWeight:"900"},techMutedText:{color:"#64748b",fontSize:9,fontWeight:"700"},
  back:{position:"absolute",zIndex:65,alignItems:"center",justifyContent:"center",backgroundColor:"rgba(5,12,20,.88)",borderWidth:1,borderColor:"rgba(148,163,184,.28)",elevation:12},backL:{left:20,top:16,width:56,height:56,borderRadius:28},backP:{left:14,top:16,width:48,height:48,borderRadius:24},center:{position:"absolute",zIndex:60,left:0,right:0,flexDirection:"row",alignItems:"center",justifyContent:"center"},centerL:{top:"50%",transform:[{translateY:-42}],gap:52},centerP:{top:"48%",transform:[{translateY:-35}],gap:26},round:{width:64,height:64,borderRadius:32,alignItems:"center",justifyContent:"center",backgroundColor:"rgba(5,12,20,.7)",borderWidth:1,borderColor:"rgba(148,163,184,.3)",elevation:7},roundP:{width:52,height:52,borderRadius:26},roundBadge:{position:"absolute",color:"#fff",fontSize:9,fontWeight:"900"},play:{width:84,height:84,borderRadius:42,padding:5,backgroundColor:"rgba(34,211,238,.18)",borderWidth:1,borderColor:"rgba(103,232,249,.58)",elevation:14},playP:{width:70,height:70,borderRadius:35},playInner:{flex:1,borderRadius:999,alignItems:"center",justifyContent:"center"},playPressed:{transform:[{scale:.95}],opacity:.92},
  bottom:{position:"absolute",zIndex:62,left:0,right:0},bottomL:{bottom:14,paddingHorizontal:24},bottomP:{bottom:10,paddingHorizontal:12},seekRow:{width:"100%",height:32,marginBottom:7,flexDirection:"row",alignItems:"center",gap:8},time:{width:54,color:"#fff",fontSize:11,fontWeight:"800",fontVariant:["tabular-nums"]},timeR:{textAlign:"right"},seekTouch:{flex:1,height:28,justifyContent:"center"},seekTrack:{height:4,borderRadius:2,backgroundColor:"rgba(226,232,240,.3)",overflow:"visible"},seekFill:{position:"absolute",left:0,top:0,bottom:0,borderRadius:2},seekThumb:{position:"absolute",top:-4,marginLeft:-6,width:12,height:12,borderRadius:6,backgroundColor:"#67e8f9",borderWidth:2,borderColor:"#e6fcff"},
  tray:{overflow:"hidden",borderWidth:1,borderColor:"rgba(71,101,124,.46)",backgroundColor:"rgba(4,9,15,.97)",elevation:12},trayL:{alignSelf:"center",minHeight:60,paddingHorizontal:9,borderRadius:22},trayP:{width:"100%",minHeight:70,paddingHorizontal:6,paddingTop:4,paddingBottom:3,borderRadius:22},glow:{position:"absolute",left:18,right:18,top:0,height:1,backgroundColor:"rgba(103,232,249,.54)"},rowL:{minHeight:58,flexDirection:"row",alignItems:"center",justifyContent:"center",gap:5},rowP:{minHeight:58,flexDirection:"row",alignItems:"center",justifyContent:"space-evenly"},
  action:{width:54,height:54,borderRadius:15,alignItems:"center",justifyContent:"center",borderWidth:1,borderColor:"transparent",backgroundColor:"rgba(15,23,42,.42)",paddingTop:3,paddingBottom:2},actionP:{flex:1,minWidth:0,maxWidth:72,height:56},actionHi:{borderColor:"rgba(34,211,238,.3)",backgroundColor:"rgba(8,145,178,.12)"},actionActive:{borderColor:"rgba(103,232,249,.72)",backgroundColor:"rgba(8,145,178,.2)"},actionPressed:{transform:[{scale:.95}],backgroundColor:"rgba(30,41,59,.88)"},iconBox:{height:29,minWidth:34,alignItems:"center",justifyContent:"center"},glyph:{color:"#fff",fontSize:15,fontWeight:"900"},glyphA:{color:"#8beeff"},actionLabel:{maxWidth:"100%",color:"#aab8c9",fontSize:8.5,lineHeight:11,fontWeight:"800",marginTop:1},actionLabelA:{color:"#fff"},badge:{position:"absolute",right:-7,top:-1,minWidth:24,maxWidth:43,height:15,paddingHorizontal:3,borderRadius:8,alignItems:"center",justifyContent:"center",backgroundColor:"rgba(8,47,73,.96)",borderWidth:1,borderColor:"rgba(103,232,249,.58)"},badgeText:{color:"#a5f3fc",fontSize:7,fontWeight:"900"},divider:{width:1,height:31,marginHorizontal:1,backgroundColor:"rgba(148,163,184,.18)"},pages:{height:5,flexDirection:"row",alignItems:"center",justifyContent:"center",gap:4},pageDot:{width:4,height:4,borderRadius:2,backgroundColor:"rgba(148,163,184,.32)"},pageDotA:{width:11,borderRadius:2,backgroundColor:"#67e8f9"},disabled:{opacity:.3},pressed:{opacity:.78,transform:[{scale:.96}]},
});
