import React, { useEffect, useMemo, useRef, useState } from "react";
import { Pressable, StyleSheet, Text, View } from "react-native";
import { FocusButton } from "@/components/FocusButton";
import { useColors } from "@/hooks/useColors";
import { readLatestIsolatedStalkerSessionForProbe } from "@/lib/stalkerIsolatedLogin";
import { discoverStalkerSeriesDetails, discoverStalkerSeriesEpisodes, probeStalkerSeriesCategories, probeStalkerSeriesCreateLink, probeStalkerSeriesPage, stalkerSeriesSeasonFieldNames, type StalkerSeriesCreateLinkObservation, type StalkerSeriesDetailDiscovery, type StalkerSeriesEpisodeDiscovery, type StalkerSeriesProbeCategory, type StalkerSeriesProbeItem, type StalkerSeriesProbeObservation } from "@/lib/stalkerSeriesProbe";

type Stage = "IDLE" | "CATEGORIES" | "PAGE" | "DETAILS" | "EPISODES" | "LINK";
function Observation({ title, value }: { title: string; value: StalkerSeriesProbeObservation | StalkerSeriesCreateLinkObservation | null }) { const colors = useColors(); if (!value) return null; return <View style={[styles.observation, { borderColor: colors.border, backgroundColor: colors.card }]}><Text style={[styles.strong, { color: colors.foreground }]}>{title}: {value.classification}</Text><Text style={{ color: colors.mutedForeground }}>shape={value.payloadShape} · http={value.httpStatus ?? "unavailable"} · count={value.itemCount}</Text>{value.totalItems !== undefined ? <Text style={{ color: colors.mutedForeground }}>total={value.totalItems} · max/page={value.maxPageItems ?? "?"} · cur_page={value.currentPage ?? "?"}</Text> : null}{value.fieldNames.length ? <Text style={{ color: colors.mutedForeground }}>fields={value.fieldNames.join(", ")}</Text> : null}{value.samplePrimitives.length ? <Text style={{ color: colors.mutedForeground }}>sample={value.samplePrimitives.join(" · ")}</Text> : null}{"resolvedScheme" in value && value.resolvedScheme ? <Text style={{ color: colors.mutedForeground }}>resolved scheme={value.resolvedScheme}</Text> : null}{"wrapperPrefix" in value ? <Text style={{ color: colors.mutedForeground }}>wrapper prefix={value.wrapperPrefix ? "YES" : "NO"}</Text> : null}{"extraTransportHints" in value ? <Text style={{ color: colors.mutedForeground }}>header/cookie hint={value.extraTransportHints ? "YES" : "NO"}</Text> : null}{value.error ? <Text style={{ color: colors.destructive }}>{value.error}</Text> : null}</View>; }
function detailLabel(d: StalkerSeriesDetailDiscovery | null) { return d?.classification ?? "IDLE"; }

export function StalkerSeriesProbePanel() {
  const colors = useColors();
  const [expanded, setExpanded] = useState(false), [stage, setStage] = useState<Stage>("IDLE"), [busy, setBusy] = useState(false);
  const [categories, setCategories] = useState<StalkerSeriesProbeCategory[]>([]), [items, setItems] = useState<StalkerSeriesProbeItem[]>([]);
  const [categoryId, setCategoryId] = useState<string | null>(null), [seriesId, setSeriesId] = useState<string | null>(null), [seasonId, setSeasonId] = useState<string | null>(null), [episodeId, setEpisodeId] = useState<string | null>(null);
  const [categoryObs, setCategoryObs] = useState<StalkerSeriesProbeObservation | null>(null), [pageObs, setPageObs] = useState<StalkerSeriesProbeObservation | null>(null), [detail, setDetail] = useState<StalkerSeriesDetailDiscovery | null>(null), [episodeDiscovery, setEpisodeDiscovery] = useState<StalkerSeriesEpisodeDiscovery | null>(null), [linkObs, setLinkObs] = useState<StalkerSeriesCreateLinkObservation | null>(null);
  const categoryStarted = useRef(false), pageStarted = useRef(false), detailStarted = useRef(false), episodeStarted = useRef(false), linkStarted = useRef(false), active = useRef<AbortController | null>(null);
  useEffect(() => () => active.current?.abort(), []);
  const signal = () => { active.current?.abort(); active.current = new AbortController(); return active.current.signal; };
  const selectable = useMemo(() => { const filtered = categories.filter((c) => c.id !== "*"); return filtered.length ? filtered : categories; }, [categories]);
  const category = selectable.find((c) => c.id === categoryId) ?? null, series = items.find((i) => i.id === seriesId) ?? null, seasons = detail?.seasons ?? [], season = seasons.find((s) => s.id === seasonId) ?? null, episodes = episodeDiscovery?.episodes ?? [], episode = episodes.find((e) => e.id === episodeId) ?? null;

  const bp1 = async () => { const s = readLatestIsolatedStalkerSessionForProbe(); if (!s || categoryStarted.current) return; categoryStarted.current = true; setBusy(true); setStage("CATEGORIES"); const r = await probeStalkerSeriesCategories(s, signal()); setCategories(r.categories); setCategoryObs(r.observation); setBusy(false); };
  const bp2 = async () => { const s = readLatestIsolatedStalkerSessionForProbe(); if (!s || !category || pageStarted.current) return; pageStarted.current = true; setBusy(true); setStage("PAGE"); const r = await probeStalkerSeriesPage(s, category, signal()); setItems(r.items); setPageObs(r.observation); setBusy(false); };
  const bp3 = async () => { const s = readLatestIsolatedStalkerSessionForProbe(); if (!s || !series || detailStarted.current) return; detailStarted.current = true; setBusy(true); setStage("DETAILS"); setDetail(await discoverStalkerSeriesDetails(s, series, signal())); setBusy(false); };
  const bp4 = async () => { const s = readLatestIsolatedStalkerSessionForProbe(); if (!s || !series || !season || episodeStarted.current) return; episodeStarted.current = true; setBusy(true); setStage("EPISODES"); setEpisodeDiscovery(await discoverStalkerSeriesEpisodes(s, series, season, signal())); setBusy(false); };
  const bp5 = async () => { const s = readLatestIsolatedStalkerSessionForProbe(); if (!s || !season || !episode || linkStarted.current) return; linkStarted.current = true; setBusy(true); setStage("LINK"); const r = await probeStalkerSeriesCreateLink(s, season, episode, signal()); setLinkObs(r.observation); setBusy(false); };

  if (!expanded) return <View style={[styles.shell, { borderColor: colors.border, backgroundColor: colors.card }]}><View style={{ flex: 1, gap: 4 }}><Text style={[styles.title, { color: colors.foreground }]}>Tanılama: Stalker Series fiziksel probu</Text><Text style={{ color: colors.mutedForeground }}>R16-D3 Diagnostic only · Production Series değildir.</Text></View><FocusButton label="Series probunu aç" icon="activity" variant="ghost" onPress={() => setExpanded(true)} /></View>;
  return <View style={[styles.panel, { borderColor: colors.primary, backgroundColor: colors.card }]}>
    <Text style={[styles.title, { color: colors.foreground }]}>R16-D3 · Season → Episode → Playback Probe</Text><Text style={{ color: colors.mutedForeground }}>Stage: {stage} · p=1 only · bounded diagnostic requests · no persistence</Text>
    <FocusButton label={busy ? "Çalışıyor" : "BP1 · SERIES CATEGORIES"} disabled={busy || categoryStarted.current} onPress={() => void bp1()} /><Observation title="BP1" value={categoryObs} />
    {categoryObs?.classification === "SUCCESS" ? <><Text style={[styles.strong, { color: colors.foreground }]}>Bir kategori seç</Text><View style={styles.list}>{selectable.map((c) => <Pressable key={c.id} disabled={pageStarted.current} onPress={() => setCategoryId(c.id)} style={[styles.row, { borderColor: categoryId === c.id ? colors.primary : colors.border }]}><Text style={{ color: colors.foreground }}>{c.title}</Text></Pressable>)}</View><FocusButton label="BP2 · SERIES LIST p=1" disabled={busy || !category || pageStarted.current} onPress={() => void bp2()} /></> : null}<Observation title="BP2" value={pageObs} />
    {pageObs?.classification === "SUCCESS" ? <><Text style={[styles.strong, { color: colors.foreground }]}>Bir Series satırı seç</Text><View style={styles.list}>{items.slice(0, 30).map((i) => <Pressable key={i.id} disabled={detailStarted.current} onPress={() => setSeriesId(i.id)} style={[styles.row, { borderColor: seriesId === i.id ? colors.primary : colors.border }]}><Text style={{ color: colors.foreground }}>{i.title}</Text></Pressable>)}</View>{series ? <Text style={{ color: colors.mutedForeground }}>selected={series.title} · raw id={series.id}</Text> : null}<FocusButton label="BP3 · SEASONS" disabled={busy || !series || detailStarted.current} onPress={() => void bp3()} /></> : null}
    {detail ? <View style={[styles.observation, { borderColor: colors.border }]}><Text style={[styles.strong, { color: colors.foreground }]}>BP3: {detailLabel(detail)}</Text><Text style={{ color: colors.mutedForeground }}>source={detail.source} · candidates={detail.candidateCount} · seasons={seasons.length} · episodes-at-season-stage={detail.episodes.length}</Text>{detail.observations.map((o) => <Text key={o.candidateNumber} style={{ color: colors.mutedForeground }}>candidate {o.candidateNumber}: {o.type}/{o.action} · keys={o.paramKeys.join(",")} · {o.hierarchyClassification}</Text>)}</View> : null}
    {seasons.length ? <><Text style={[styles.strong, { color: colors.foreground }]}>Bir season seç</Text><View style={styles.list}>{seasons.map((s) => <Pressable key={s.id} disabled={episodeStarted.current && seasonId !== s.id} onPress={() => { setSeasonId(s.id); setEpisodeId(null); setEpisodeDiscovery(null); }} style={[styles.row, { borderColor: seasonId === s.id ? colors.primary : colors.border }]}><Text style={{ color: colors.foreground }}>{s.label} · id={s.id}</Text></Pressable>)}</View></> : null}
    {season ? <><Text style={{ color: colors.mutedForeground }}>selected season={season.label} · id={season.id}</Text><Text style={{ color: colors.mutedForeground }}>season fields={stalkerSeriesSeasonFieldNames(season).join(", ") || "none"}</Text><FocusButton label="BP4 · EPISODES" disabled={busy || episodeStarted.current} onPress={() => void bp4()} /></> : null}
    {episodeDiscovery ? <View style={[styles.observation, { borderColor: colors.border }]}><Text style={[styles.strong, { color: colors.foreground }]}>BP4: {episodeDiscovery.classification}</Text><Text style={{ color: colors.mutedForeground }}>source={episodeDiscovery.source} · candidates={episodeDiscovery.candidateCount} · episodes={episodes.length}</Text>{episodeDiscovery.observations.map((o) => <Text key={o.candidateNumber} style={{ color: colors.mutedForeground }}>candidate {o.candidateNumber}: {o.type}/{o.action} · keys={o.paramKeys.join(",")} · {o.hierarchyClassification}</Text>)}</View> : null}
    {episodes.length ? <><Text style={[styles.strong, { color: colors.foreground }]}>Bir episode seç</Text><View style={styles.list}>{episodes.map((e) => <Pressable key={e.id} disabled={episodeId !== null && episodeId !== e.id} onPress={() => setEpisodeId(e.id)} style={[styles.row, { borderColor: episodeId === e.id ? colors.primary : colors.border }]}><Text style={{ color: colors.foreground }}>{e.label}</Text></Pressable>)}</View></> : null}
    {episode ? <><Text style={{ color: colors.mutedForeground }}>selected episode={episode.label} · id={episode.id}</Text><FocusButton label="BP5 · PLAYBACK DIALECT" disabled={busy || linkStarted.current || !season} onPress={() => void bp5()} /></> : null}<Observation title="BP5" value={linkObs} />
  </View>;
}
const styles = StyleSheet.create({ shell: { borderWidth: 1, borderRadius: 14, padding: 14, flexDirection: "row", alignItems: "center", gap: 12, marginTop: 18 }, panel: { borderWidth: 1, borderRadius: 14, padding: 14, gap: 10, marginTop: 18 }, title: { fontWeight: "900", fontSize: 16 }, strong: { fontWeight: "800" }, list: { gap: 6 }, row: { borderWidth: 1, borderRadius: 10, padding: 10 }, observation: { borderWidth: 1, borderRadius: 10, padding: 10, gap: 3 } });
