import { redactSensitiveText, safeLog } from "./safeLog";
import { StalkerPortalError } from "./stalkerPortal";
import type { StalkerIsolatedSession } from "./stalkerIsolatedLogin";

export type StalkerSeriesProbeClassification = "SUCCESS" | "EMPTY" | "UNSUPPORTED" | "ERROR" | "EVIDENCE_REQUIRED";
export type StalkerSeriesHierarchyClassification = "SEASONS_FOUND" | "EPISODES_FOUND" | "SERIES_DETAIL_FOUND" | "EMPTY" | "UNSUPPORTED" | "ERROR" | "EVIDENCE_REQUIRED";
export type StalkerSeriesProbeObservation = { classification: StalkerSeriesProbeClassification; httpStatus: number | null; payloadShape: string; itemCount: number; totalItems?: number; maxPageItems?: number; currentPage?: number; fieldNames: string[]; samplePrimitives: string[]; error?: string };
export type StalkerSeriesProbeCategory = { id: string; title: string };
export type StalkerSeriesProbeItem = { id: string; title: string; raw: Record<string, unknown> };
export type StalkerSeriesNestedContainer = { path: string; rows: Record<string, unknown>[] };
export type StalkerSeriesSeason = { id: string; label: string; rows: Record<string, unknown>[] };
export type StalkerSeriesEpisode = { id: string; label: string; seasonId: string; row: Record<string, unknown> };
export type StalkerSeriesCandidateObservation = { candidateNumber: number; type: string; action: string; paramKeys: string[]; observation: StalkerSeriesProbeObservation; hierarchyClassification: StalkerSeriesHierarchyClassification; nestedContainerPaths: string[] };
export type StalkerSeriesDetailDiscovery = { classification: StalkerSeriesHierarchyClassification; source: "SELECTED_ROW" | "CANDIDATE_1" | "CANDIDATE_2" | "EVIDENCE_REQUEST" | "NONE"; containers: StalkerSeriesNestedContainer[]; seasons: StalkerSeriesSeason[]; episodes: StalkerSeriesEpisode[]; candidateCount: number; candidateNumberUsed: number | null; observations: StalkerSeriesCandidateObservation[]; payload?: unknown };
export type StalkerSeriesEpisodeDiscovery = { classification: StalkerSeriesHierarchyClassification; source: "EMBEDDED" | "EPISODE_CANDIDATE_1" | "EPISODE_CANDIDATE_2" | "NONE"; episodes: StalkerSeriesEpisode[]; candidateCount: number; candidateNumberUsed: number | null; observations: StalkerSeriesCandidateObservation[] };
export type StalkerSeriesCreateLinkObservation = StalkerSeriesProbeObservation & { resolvedScheme?: string; wrapperPrefix: boolean; returnedFieldNames: string[]; extraTransportHints: boolean };

type Params = Record<string, string | number | boolean | undefined>;
type BoundedResult = { payload: unknown; observation: StalkerSeriesProbeObservation };
const TIMEOUT = 12_000, MAX_DETAIL = 3, MAX_EPISODE = 2, MAX_PLAYBACK = 1, MAX_ROWS = 30, MAX_CONTAINERS = 12;
const unsupportedPattern = /\b(?:unknown|unsupported|not\s+implemented|not\s+available)\b/i;
const sensitiveKey = /(?:cmd|url|uri|token|auth|cookie|mac|password|secret|credential|user)/i;
const episodeKeys = ["episode", "episode_id", "episode_num", "episode_number"] as const;
const seasonKeys = ["season_id", "season", "season_number", "season_num", "season_name"] as const;
const allowedEvidenceKeys = new Set(["movie_id", "series_id", "season_id", "episode_id", "season", "id", "p"]);

const obj = (v: unknown): Record<string, unknown> | null => v && typeof v === "object" && !Array.isArray(v) ? v as Record<string, unknown> : null;
const text = (v: unknown) => typeof v === "string" && v.trim() ? v.trim() : typeof v === "number" && Number.isFinite(v) ? String(v) : "";
const has = (row: Record<string, unknown>, keys: readonly string[]) => keys.some((k) => text(row[k]) !== "");
const shape = (v: unknown) => Array.isArray(v) ? "array" : v === null ? "null" : typeof v;
const finite = (v: unknown) => { const n = typeof v === "number" ? v : typeof v === "string" && v.trim() ? Number(v) : Number.NaN; return Number.isFinite(n) ? n : undefined; };
function rows(payload: unknown): unknown[] { if (Array.isArray(payload)) return payload; const r = obj(payload); if (Array.isArray(r?.data)) return r.data; if (Array.isArray(r?.js)) return r.js; const d = obj(r?.data); if (Array.isArray(d?.data)) return d.data; if (Array.isArray(d?.items)) return d.items; return []; }
function safeSamples(row: Record<string, unknown> | null) { if (!row) return []; const out: string[] = []; for (const key of Object.keys(row).sort()) { if (sensitiveKey.test(key)) continue; const v = row[key]; if (!["string", "number", "boolean"].includes(typeof v)) continue; out.push(`${key}=${redactSensitiveText(String(v)).slice(0, 80)}`); if (out.length === 6) break; } return out; }
export function observeStalkerSeriesPayload(payload: unknown, classification?: StalkerSeriesProbeClassification): StalkerSeriesProbeObservation { const rs = rows(payload), root = obj(payload), d = obj(root?.data), first = obj(rs[0]) ?? root; const unsupported = typeof payload === "string" ? unsupportedPattern.test(payload) : root ? [root.error, root.message, root.reason, root.status].some((v) => typeof v === "string" && unsupportedPattern.test(v)) : false; const read = (k: string) => root?.[k] ?? d?.[k]; const totalItems = finite(read("total_items") ?? read("total")), maxPageItems = finite(read("max_page_items") ?? read("max_page_size")), currentPage = finite(read("cur_page") ?? read("current_page") ?? read("page") ?? read("p")); return { classification: classification ?? (unsupported ? "UNSUPPORTED" : rs.length ? "SUCCESS" : "EMPTY"), httpStatus: null, payloadShape: shape(payload), itemCount: rs.length, ...(totalItems === undefined ? {} : { totalItems }), ...(maxPageItems === undefined ? {} : { maxPageItems }), ...(currentPage === undefined ? {} : { currentPage }), fieldNames: first ? Object.keys(first).sort().slice(0, 32) : [], samplePrimitives: safeSamples(first) }; }
function errorObs(caught: unknown): StalkerSeriesProbeObservation { const message = caught instanceof Error ? caught.message : String(caught); return { classification: unsupportedPattern.test(message) ? "UNSUPPORTED" : "ERROR", httpStatus: caught instanceof StalkerPortalError ? caught.status ?? null : null, payloadShape: "error", itemCount: 0, fieldNames: [], samplePrimitives: [], error: redactSensitiveText(message) }; }
function linkedSignal(external?: AbortSignal) { const c = new AbortController(), abort = () => c.abort(); external?.addEventListener("abort", abort, { once: true }); if (external?.aborted) c.abort(); const timer = setTimeout(abort, TIMEOUT); return { signal: c.signal, cleanup: () => { clearTimeout(timer); external?.removeEventListener("abort", abort); } }; }
async function request(session: StalkerIsolatedSession, params: Params, n: number, signal?: AbortSignal): Promise<BoundedResult> { const linked = linkedSignal(signal); safeLog.info("SERIES_PROBE_REQUEST", { type: params.type, action: params.action, param_keys: Object.keys(params).filter((k) => k !== "type" && k !== "action").sort(), candidate_number: n }); try { const payload = await session.request(params, linked.signal, undefined, { providerId: "r16-d3-series-probe" }); const observation = observeStalkerSeriesPayload(payload); safeLog.info("SERIES_PROBE_RESPONSE", { http_status: observation.httpStatus, payload_shape: observation.payloadShape, item_count: observation.itemCount, total_items: observation.totalItems, field_names: observation.fieldNames, classification: observation.classification }); return { payload, observation }; } catch (e) { const observation = errorObs(e); safeLog.info("SERIES_PROBE_RESPONSE", { http_status: observation.httpStatus, payload_shape: observation.payloadShape, item_count: 0, field_names: [], classification: observation.classification, error: observation.error }); return { payload: undefined, observation }; } finally { linked.cleanup(); } }

export async function probeStalkerSeriesCategories(session: StalkerIsolatedSession, signal?: AbortSignal) { const r = await request(session, { type: "series", action: "get_categories" }, 1, signal); const categories: StalkerSeriesProbeCategory[] = [], seen = new Set<string>(); for (const raw of rows(r.payload)) { const row = obj(raw), id = text(row?.id), title = text(row?.title); if (row && id && title && !seen.has(id)) { seen.add(id); categories.push({ id, title }); } } return { categories, observation: { ...r.observation, classification: r.observation.classification === "SUCCESS" && !categories.length ? "EMPTY" as const : r.observation.classification } }; }
export async function probeStalkerSeriesPage(session: StalkerIsolatedSession, category: StalkerSeriesProbeCategory, signal?: AbortSignal) { const r = await request(session, { type: "series", action: "get_ordered_list", category: category.id, p: 1 }, 1, signal); const items: StalkerSeriesProbeItem[] = [], seen = new Set<string>(); for (const raw of rows(r.payload)) { const row = obj(raw); if (!row) continue; const id = text(row.id) || text(row.series_id), title = text(row.name) || text(row.title) || id; if (id && !seen.has(id)) { seen.add(id); items.push({ id, title, raw: row }); } } return { items, observation: { ...r.observation, classification: r.observation.classification === "SUCCESS" && !items.length ? "EMPTY" as const : r.observation.classification } }; }

export function inspectStalkerSeriesNestedContainers(value: unknown) { const out: StalkerSeriesNestedContainer[] = [], seen = new Set<object>(); const walk = (cur: unknown, path: string, depth: number) => { if (depth > 4 || out.length >= MAX_CONTAINERS) return; if (Array.isArray(cur)) { const rs = cur.slice(0, MAX_ROWS).map(obj).filter((r): r is Record<string, unknown> => Boolean(r)); if (rs.length) out.push({ path: path || "$", rows: rs }); rs.slice(0, 6).forEach((r, i) => walk(r, `${path || "$"}[${i}]`, depth + 1)); return; } const row = obj(cur); if (!row || seen.has(row)) return; seen.add(row); for (const [k, v] of Object.entries(row)) if (v && typeof v === "object") walk(v, path ? `${path}.${k}` : k, depth + 1); }; walk(value, "", 0); return out; }
function seasonId(row: Record<string, unknown>) { for (const k of seasonKeys) { const v = text(row[k]); if (v) return v; } return "unassigned"; }
function rowLabel(row: Record<string, unknown>) { for (const k of ["title", "name", "episode", "episode_number", "episode_num", "id"]) { const v = text(row[k]); if (v) return redactSensitiveText(v).slice(0, 80); } return `fields: ${Object.keys(row).sort().slice(0, 5).join(", ")}`; }
function hierarchyRows(payload: unknown) { const out: Record<string, unknown>[] = [], seen = new Set<Record<string, unknown>>(), append = (r: Record<string, unknown>) => { if (!seen.has(r) && out.length < MAX_ROWS) { seen.add(r); out.push(r); } }; rows(payload).map(obj).filter((r): r is Record<string, unknown> => Boolean(r)).forEach(append); inspectStalkerSeriesNestedContainers(payload).forEach((c) => c.rows.forEach(append)); return out; }
export function extractStalkerSeriesHierarchy(payload: unknown) { const all = hierarchyRows(payload); const episodeRows = all.filter((r) => has(r, episodeKeys)); const seasonRows = all.filter((r) => has(r, seasonKeys)); const map = new Map<string, Record<string, unknown>[]>(); [...seasonRows, ...episodeRows].forEach((r) => { const id = seasonId(r), bucket = map.get(id) ?? []; if (!bucket.includes(r)) bucket.push(r); map.set(id, bucket); }); const seasons = [...map.entries()].slice(0, MAX_ROWS).map(([id, rs]) => ({ id, label: id === "unassigned" ? "Season grouping unavailable" : `Season ${redactSensitiveText(id).slice(0, 40)}`, rows: rs.slice(0, MAX_ROWS) })); const episodes = episodeRows.slice(0, MAX_ROWS).map((r, i) => ({ id: text(r.episode_id) || text(r.episode_num) || text(r.episode_number) || text(r.id) || `episode-${i + 1}`, label: rowLabel(r), seasonId: seasonId(r), row: r })); return { seasons, episodes }; }
function classify(payload: unknown, observation: StalkerSeriesProbeObservation): StalkerSeriesHierarchyClassification { if (observation.classification === "UNSUPPORTED") return "UNSUPPORTED"; if (observation.classification === "ERROR") return "ERROR"; const h = extractStalkerSeriesHierarchy(payload); if (h.episodes.length) return "EPISODES_FOUND"; if (h.seasons.length) return "SEASONS_FOUND"; if (observation.classification === "EMPTY") return "EMPTY"; return inspectStalkerSeriesNestedContainers(payload).length || observation.fieldNames.length ? "SERIES_DETAIL_FOUND" : "EVIDENCE_REQUIRED"; }
function record(n: number, params: Params, r: BoundedResult): StalkerSeriesCandidateObservation { return { candidateNumber: n, type: text(params.type), action: text(params.action), paramKeys: Object.keys(params).filter((k) => k !== "type" && k !== "action").sort(), observation: r.observation, hierarchyClassification: classify(r.payload, r.observation), nestedContainerPaths: inspectStalkerSeriesNestedContainers(r.payload).map((c) => c.path) }; }
function detail(source: StalkerSeriesDetailDiscovery["source"], payload: unknown, count: number, used: number | null, observations: StalkerSeriesCandidateObservation[]): StalkerSeriesDetailDiscovery { const h = extractStalkerSeriesHierarchy(payload), observation = used == null ? observeStalkerSeriesPayload(payload) : observations.at(-1)?.observation ?? observeStalkerSeriesPayload(payload); return { classification: classify(payload, observation), source, containers: inspectStalkerSeriesNestedContainers(payload), seasons: h.seasons, episodes: h.episodes, candidateCount: count, candidateNumberUsed: used, observations, payload }; }
const hierarchyOk = (c: StalkerSeriesHierarchyClassification) => c === "SEASONS_FOUND" || c === "EPISODES_FOUND";
function evidenceRequestDescriptor(value: unknown): Params | null { const seen = new Set<object>(); let found: Params | null = null; const walk = (current: unknown, depth: number) => { if (found || depth > 4) return; if (Array.isArray(current)) { current.slice(0, 8).forEach((item) => walk(item, depth + 1)); return; } const row = obj(current); if (!row || seen.has(row)) return; seen.add(row); const type = text(row.type), action = text(row.action); if ((type === "series" || type === "vod") && /^get_[a-z0-9_]+$/i.test(action)) { const descriptor: Params = { type, action }; let safe = true; for (const [key, item] of Object.entries(row)) { if (key === "type" || key === "action" || !allowedEvidenceKeys.has(key)) continue; if (typeof item !== "string" && typeof item !== "number" && typeof item !== "boolean") continue; if (key === "p" && Number(item) !== 1) { safe = false; break; } descriptor[key] = item; } if (safe) found = descriptor; } Object.values(row).forEach((nested) => { if (!found && nested && typeof nested === "object") walk(nested, depth + 1); }); }; walk(value, 0); return found; }
function fingerprint(params: Params) { return Object.keys(params).sort().map((key) => `${key}=${String(params[key])}`).join("&"); }
export async function discoverStalkerSeriesDetails(session: StalkerIsolatedSession, item: StalkerSeriesProbeItem, signal?: AbortSignal): Promise<StalkerSeriesDetailDiscovery> { const direct = detail("SELECTED_ROW", item.raw, 0, null, []); if (hierarchyOk(direct.classification)) return direct; const candidates: Params[] = [{ type: "series", action: "get_ordered_list", movie_id: item.id, p: 1 }, { type: "vod", action: "get_ordered_list", movie_id: item.id, season_id: 0, episode_id: 0, p: 1 }], observations: StalkerSeriesCandidateObservation[] = [], payloads: unknown[] = [item.raw], tried = new Set<string>(); for (let i = 0; i < candidates.length && !signal?.aborted; i++) { const params = candidates[i]!; tried.add(fingerprint(params)); const r = await request(session, params, i + 1, signal); payloads.push(r.payload); observations.push(record(i + 1, params, r)); const d = detail(i ? "CANDIDATE_2" : "CANDIDATE_1", r.payload, i + 1, i + 1, observations); if (hierarchyOk(d.classification)) return d; } let candidate3: Params | null = null; for (const payload of payloads) { const descriptor = evidenceRequestDescriptor(payload); if (descriptor && !tried.has(fingerprint(descriptor))) { candidate3 = descriptor; break; } } if (candidate3 && observations.length < MAX_DETAIL && !signal?.aborted) { const r = await request(session, candidate3, 3, signal); observations.push(record(3, candidate3, r)); const d = detail("EVIDENCE_REQUEST", r.payload, 3, 3, observations); if (hierarchyOk(d.classification)) return d; } const last = observations.at(-1); return { classification: signal?.aborted ? "ERROR" : last?.hierarchyClassification === "UNSUPPORTED" ? "UNSUPPORTED" : last?.hierarchyClassification === "ERROR" ? "ERROR" : last?.hierarchyClassification === "EMPTY" ? "EMPTY" : "EVIDENCE_REQUIRED", source: "NONE", containers: [], seasons: [], episodes: [], candidateCount: observations.length, candidateNumberUsed: null, observations }; }
export function seriesProbeRowLabel(row: Record<string, unknown>) { return rowLabel(row); }

function embedded(season: StalkerSeriesSeason) { const episodes: StalkerSeriesEpisode[] = [], seen = new Set<string>(); const append = (v: unknown) => { const o = obj(v), id = o ? text(o.episode_id) || text(o.episode_num) || text(o.episode_number) || text(o.id) : text(v); if (!id || seen.has(id) || episodes.length >= MAX_ROWS) return; seen.add(id); episodes.push({ id, label: o ? rowLabel(o) : `Episode ${redactSensitiveText(id).slice(0, 40)}`, seasonId: season.id, row: o ?? { episode_id: id } }); }; for (const row of season.rows) for (const key of ["series", "episodes"] as const) if (Array.isArray(row[key])) row[key].slice(0, MAX_ROWS).forEach(append); return episodes; }
function episodesFrom(payload: unknown, season: StalkerSeriesSeason) { const explicit = extractStalkerSeriesHierarchy(payload).episodes.filter((e) => e.seasonId === season.id || e.seasonId === "unassigned"); if (explicit.length) return explicit; const matching = hierarchyRows(payload).filter((r) => seasonId(r) === season.id || seasonId(r) === "unassigned"); return embedded({ ...season, rows: [...season.rows, ...matching] }); }
const supportsE2 = (season: StalkerSeriesSeason) => season.rows.some((r) => ["category", "genre", "genre_id"].some((k) => Object.prototype.hasOwnProperty.call(r, k)));
export async function discoverStalkerSeriesEpisodes(session: StalkerIsolatedSession, item: StalkerSeriesProbeItem, season: StalkerSeriesSeason, signal?: AbortSignal): Promise<StalkerSeriesEpisodeDiscovery> { const direct = embedded(season); if (direct.length) return { classification: "EPISODES_FOUND", source: "EMBEDDED", episodes: direct, candidateCount: 0, candidateNumberUsed: null, observations: [] }; const observations: StalkerSeriesCandidateObservation[] = []; const e1: Params = { type: "series", action: "get_ordered_list", movie_id: item.id, season_id: season.id, episode_id: 0, p: 1 }; const r1 = await request(session, e1, 1, signal); observations.push(record(1, e1, r1)); const ep1 = episodesFrom(r1.payload, season); if (ep1.length) return { classification: "EPISODES_FOUND", source: "EPISODE_CANDIDATE_1", episodes: ep1, candidateCount: 1, candidateNumberUsed: 1, observations }; const c1 = observations[0]!.hierarchyClassification; if (!signal?.aborted && (c1 === "EMPTY" || c1 === "UNSUPPORTED") && supportsE2(season)) { const e2: Params = { type: "series", action: "get_ordered_list", movie_id: item.id, category: item.id, genre: "*", season_id: season.id, episode_id: 0, p: 1 }; const r2 = await request(session, e2, 2, signal); observations.push(record(2, e2, r2)); const ep2 = episodesFrom(r2.payload, season); if (ep2.length) return { classification: "EPISODES_FOUND", source: "EPISODE_CANDIDATE_2", episodes: ep2, candidateCount: 2, candidateNumberUsed: 2, observations }; } const last = observations.at(-1); return { classification: signal?.aborted ? "ERROR" : last?.hierarchyClassification === "UNSUPPORTED" ? "UNSUPPORTED" : last?.hierarchyClassification === "ERROR" ? "ERROR" : last?.hierarchyClassification === "EMPTY" ? "EMPTY" : "EVIDENCE_REQUIRED", source: "NONE", episodes: [], candidateCount: observations.length, candidateNumberUsed: null, observations }; }

function seasonCmd(season: StalkerSeriesSeason) { for (const row of season.rows) if (typeof row.cmd === "string" && row.cmd.trim()) return row.cmd; return ""; }
function resolved(payload: unknown) { const values: string[] = []; if (typeof payload === "string") values.push(payload); const root = obj(payload); if (root) Object.values(root).forEach((v) => { if (typeof v === "string") values.push(v); }); for (const value of values) { const wrapperPrefix = /^ffmpeg\s+/i.test(value.trim()), source = value.replace(/^ffmpeg\s+/i, "").trim(); try { const u = new URL(source); if (["http:", "https:", "rtsp:", "rtmp:"].includes(u.protocol)) return { scheme: u.protocol.replace(":", ""), wrapperPrefix }; } catch { /* ignore non-URL fields */ } } return null; }
export async function probeStalkerSeriesCreateLink(session: StalkerIsolatedSession, season: StalkerSeriesSeason, episode: StalkerSeriesEpisode, signal?: AbortSignal): Promise<{ observation: StalkerSeriesCreateLinkObservation }> { const cmd = seasonCmd(season); if (!cmd || !episode.id) return { observation: { classification: "EVIDENCE_REQUIRED", httpStatus: null, payloadShape: "none", itemCount: 0, fieldNames: [], samplePrimitives: [], wrapperPrefix: false, returnedFieldNames: [], extraTransportHints: false } }; const r = await request(session, { type: "vod", action: "create_link", cmd, series: episode.id }, 1, signal); const hit = resolved(r.payload), root = obj(r.payload), returnedFieldNames = root ? Object.keys(root).sort().slice(0, 32) : []; return { observation: { ...r.observation, classification: hit ? "SUCCESS" : r.observation.classification === "SUCCESS" ? "EMPTY" : r.observation.classification, resolvedScheme: hit?.scheme, wrapperPrefix: hit?.wrapperPrefix ?? false, returnedFieldNames, extraTransportHints: returnedFieldNames.some((k) => /header|cookie/i.test(k)) } }; }
export function stalkerSeriesSeasonFieldNames(season: StalkerSeriesSeason) { const names = new Set<string>(); season.rows.forEach((r) => Object.keys(r).forEach((k) => names.add(k))); return [...names].sort().slice(0, 32); }
export const STALKER_SERIES_PROBE_LIMITS = { page: 1, maxCategorySelections: 1, maxSeriesSelections: 1, maxEvidenceCandidates: MAX_DETAIL, maxSeasonSelections: 1, maxEpisodeListCandidates: MAX_EPISODE, maxEpisodeSelections: 1, maxPlaybackCandidates: MAX_PLAYBACK, maxCreateLinks: MAX_PLAYBACK, timeoutMs: TIMEOUT } as const;
