import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { beginStalkerPlaybackTrace, clearStalkerTraceEntries, getStalkerTraceEntries, traceStalker } from "../lib/stalkerPlaybackTrace";
import { projectC3HPhysicalTrace } from "../lib/c3hPhysicalTraceProjection";
const ROOT=resolve(dirname(fileURLToPath(import.meta.url)),"..");
const source=(p:string)=>readFileSync(resolve(ROOT,p),"utf8");
let passed=0;
async function scenario(name:string,run:()=>void|Promise<void>){clearStalkerTraceEntries();await run();passed+=1;console.log(`ok ${passed} - ${name}`);}
function tap(){const traceId=beginStalkerPlaybackTrace();traceStalker("STALKER_LIVE_TAP",{traceId});traceStalker("PLAYBACK_REACQUIRE_START",{traceId});return traceId;}
async function main(){
 await scenario("A one provider attempt remains one independent row",()=>{const t=tap();traceStalker("C3K_ATTEMPT_START",{traceId:t,attemptSeq:1,attemptKind:"GENRE"});traceStalker("C3K_ATTEMPT_DONE",{traceId:t,attemptSeq:1,attemptKind:"GENRE",attemptResult:"OK",durationMs:200,networkMs:190,yieldMs:2,parseMs:1,requestCount:1});assert.deepEqual(projectC3HPhysicalTrace(getStalkerTraceEntries()).c3kAttempts.map(x=>[x.sequence,x.kind,x.result]),[[1,"GENRE","OK"]]);});
 await scenario("B compatibility reject remains after later success",()=>{const t=tap();for(const [seq,kind,result,ms] of [[1,"GENRE_ID","COMPAT_REJECT",5200],[2,"GENRE","OK",1300]] as const){traceStalker("C3K_ATTEMPT_START",{traceId:t,attemptSeq:seq,attemptKind:kind});traceStalker("C3K_ATTEMPT_DONE",{traceId:t,attemptSeq:seq,attemptKind:kind,attemptResult:result,durationMs:ms,networkMs:ms-10,yieldMs:4,parseMs:1,requestCount:1});}assert.deepEqual(projectC3HPhysicalTrace(getStalkerTraceEntries()).c3kAttempts.map(x=>[x.sequence,x.result]),[[1,"COMPAT_REJECT"],[2,"OK"]]);});
 await scenario("C attempt rows order by start sequence",()=>{const t=tap();traceStalker("C3K_ATTEMPT_START",{traceId:t,attemptSeq:2,attemptKind:"GENRE"});traceStalker("C3K_ATTEMPT_START",{traceId:t,attemptSeq:1,attemptKind:"GENRE_ID"});assert.deepEqual(projectC3HPhysicalTrace(getStalkerTraceEntries()).c3kAttempts.map(x=>x.sequence),[1,2]);});
 await scenario("D N Y P and request count stay attempt scoped",()=>{const t=tap();traceStalker("C3K_ATTEMPT_START",{traceId:t,attemptSeq:1,attemptKind:"DUAL"});traceStalker("C3K_ATTEMPT_DONE",{traceId:t,attemptSeq:1,attemptKind:"DUAL",attemptResult:"OK",durationMs:20,networkMs:11,yieldMs:3,parseMs:2,requestCount:2});const r=projectC3HPhysicalTrace(getStalkerTraceEntries()).c3kAttempts[0];assert.deepEqual([r?.networkMs,r?.yieldMs,r?.parseMs,r?.requestCount],[11,3,2,2]);});
 await scenario("E new playback clears prior summary and attempts",()=>{const a=tap();traceStalker("C3K_ATTEMPT_START",{traceId:a,attemptSeq:1,attemptKind:"GENRE"});traceStalker("PLAYBACK_REACQUIRE_DONE",{traceId:a});const b=beginStalkerPlaybackTrace();traceStalker("STALKER_LIVE_TAP",{traceId:b});traceStalker("PLAYBACK_REACQUIRE_START",{traceId:b});const p=projectC3HPhysicalTrace(getStalkerTraceEntries());assert.equal(p.reacquireMs,null);assert.equal(p.c3fMs,null);assert.equal(p.vlcStartMs,null);assert.equal(p.totalMs,null);assert.deepEqual(p.c3kAttempts,[]);});
 await scenario("F late previous trace attempt ignored",()=>{const a=tap();const b=beginStalkerPlaybackTrace();traceStalker("STALKER_LIVE_TAP",{traceId:b});traceStalker("PLAYBACK_REACQUIRE_START",{traceId:b});traceStalker("C3K_ATTEMPT_DONE",{traceId:a,attemptSeq:1,attemptKind:"GENRE",attemptResult:"OK",durationMs:9999});assert.deepEqual(projectC3HPhysicalTrace(getStalkerTraceEntries()).c3kAttempts,[]);});
 await scenario("G accounting is authoritative and never negative",()=>{const t=tap();traceStalker("C3K_ATTEMPT_START",{traceId:t,attemptSeq:1,attemptKind:"GENRE"});traceStalker("C3K_ATTEMPT_DONE",{traceId:t,attemptSeq:1,attemptKind:"GENRE",attemptResult:"OK",durationMs:200});traceStalker("PLAYBACK_REACQUIRE_DONE",{traceId:t});const p=projectC3HPhysicalTrace(getStalkerTraceEntries());assert.equal(p.accountedMs,200);assert.ok((p.unaccountedMs??0)>=0);});
 await scenario("H incomplete boundaries report unknown accounting",()=>{const t=tap();traceStalker("C3K_ATTEMPT_START",{traceId:t,attemptSeq:1,attemptKind:"GENRE"});assert.equal(projectC3HPhysicalTrace(getStalkerTraceEntries()).accountedMs,null);});
 await scenario("I secret-like fields are excluded",()=>{const t=tap();traceStalker("C3K_ATTEMPT_START",{traceId:t,attemptSeq:1,attemptKind:"GENRE",url:"http://secret",cmd:"secret-cmd",portalId:"secret-id",categoryId:"secret-category",page:7} as any);const rendered=JSON.stringify(projectC3HPhysicalTrace(getStalkerTraceEntries()));for(const secret of ["http://secret","secret-id","secret-category","secret-cmd"]){assert.equal(rendered.includes(secret),false);}});
 await scenario("J closed attempt enums reject arbitrary strings",()=>{const t=tap();traceStalker("C3K_ATTEMPT_START",{traceId:t,attemptSeq:1,attemptKind:"http://secret",attemptResult:"Bearer"} as any);const e=getStalkerTraceEntries().find(x=>x.event==="C3K_ATTEMPT_START");assert.equal(e?.details.attemptKind,undefined);assert.equal(e?.details.attemptResult,undefined);});
 await scenario("K diagnostic memory remains bounded and fail open",()=>{const src=source("lib/stalkerPlaybackTrace.ts");assert.match(src,/MAX_ENTRIES = 180/);assert.match(src,/try\{listener\(\);\}catch/);});
 await scenario("L dialect order and cache remain unchanged",()=>{const src=source("lib/stalkerPagedCatalog.ts");assert.match(src,/\["genre_id", "genre", "dual"\]/);assert.match(src,/dialectByProvider\.set\(options\.providerId, dialect\)/);});
 await scenario("M exact/category/full decision semantics remain unchanged",()=>{const src=source("lib/stalkerLiveRuntimeLocator.ts");assert.match(src,/if \(exact\) return \{ channel: exact, source: "EXACT_PAGE"/);assert.match(src,/return bounded \?\? fullDiscovery\(\)/);});
 await scenario("N C3F and VLC remain untouched by C3K",()=>{const loc=source("lib/stalkerLiveRuntimeLocator.ts");assert.doesNotMatch(loc,/classifyStalkerLiveRuntimeCmd|resolveStalkerLiveRuntimeCmd/);const overlay=source("components/debug/C3HPhysicalTraceOverlay.tsx");assert.match(overlay,/C3K ATTEMPTS/);});
 await scenario("O attempt instrumentation exposes no identity fields",()=>{const src=source("lib/c3hPhysicalTraceProjection.ts");assert.doesNotMatch(src,/categoryId|portalId|channelId|streamId|username|password|play_token/);});
 assert.equal(passed,15);console.log("C3K provider attempt correlation scenarios: 15/15 passed");
}
void main().catch(e=>{console.error(e);process.exitCode=1;});
