import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { beginStalkerPlaybackTrace, clearStalkerTraceEntries, describePlaybackSourceSafely, formatStalkerTrace, getStalkerTraceEntries, shouldTraceStalkerBuffering, traceStalker } from "../lib/stalkerPlaybackTrace";
const ROOT=resolve(dirname(fileURLToPath(import.meta.url)),".."); const source=(p:string)=>readFileSync(resolve(ROOT,p),"utf8");
clearStalkerTraceEntries(); const traceId=beginStalkerPlaybackTrace();
traceStalker("SAFETY_TEST",{traceId,providerShortId:"abcd1234",stage:"DISCOVERY",errorClass:"DISCOVERY_ERROR",mac:"00:11:22:33:44:55",username:"user-secret",password:"pass-secret",token:"token-secret",cookie:"cookie-secret",cmd:"ffmpeg http://secret/cmd",url:"http://secret/stream"} as Record<string,string>);
const output=formatStalkerTrace(getStalkerTraceEntries());
for(const forbidden of ["00:11:22:33:44:55","user-secret","pass-secret","token-secret","cookie-secret","ffmpeg http://secret/cmd","http://secret/stream"]) assert.equal(output.includes(forbidden),false);
assert.match(output,/"stage":"DISCOVERY"/); assert.match(output,/"errorClass":"DISCOVERY_ERROR"/);
const secretUrl="http://user:pass@example.invalid/live/token/196699.ts?token=super-secret&x=1"; const metadata=describePlaybackSourceSafely(secretUrl); assert.equal(metadata.scheme,"http"); assert.equal(metadata.looksLikeTransportStream,true); assert.equal(metadata.hasQuery,true); assert.equal(metadata.queryKeyCount,2); assert.equal(JSON.stringify(metadata).includes(secretUrl),false); assert.equal(JSON.stringify(metadata).includes("example.invalid"),false); assert.equal(JSON.stringify(metadata).includes("super-secret"),false); assert.equal(shouldTraceStalkerBuffering(traceId,0),true); assert.equal(shouldTraceStalkerBuffering(traceId,12),false); assert.equal(shouldTraceStalkerBuffering(traceId,25),true); assert.equal(shouldTraceStalkerBuffering(traceId,49),false); assert.equal(shouldTraceStalkerBuffering(traceId,50),true); assert.equal(shouldTraceStalkerBuffering(traceId,75),true); assert.equal(shouldTraceStalkerBuffering(traceId,100),true);
assert.doesNotMatch(source("lib/stalkerPlaybackTrace.ts"),/AsyncStorage|SecureStore|FileSystem|setItem\(|writeFile/);
assert.match(source("lib/catalogRuntime.ts"),/resolveStalkerLiveCreateLink\)\(session, currentChannel\.cmd, signal\)/);
assert.match(source("components/ProductShell.tsx"),/<StalkerMainPage key=\{provider\.id\}/);
assert.match(source("components/CompatibilityVideoPlayerV2.tsx"),/PLAYER_SOURCE_TRANSITION/); assert.match(source("components/CompatibilityVideoPlayerV2.tsx"),/PLAYER_PROGRESS_RESTORE/); assert.match(source("components\/player\/VlcPlaybackSurface.tsx"),/VLC_SOURCE_SET|VLC_OPENING/); assert.match(source("components/player/VlcPlaybackSurface.tsx"),/VLC_PLAYING/); assert.match(source("components/player/VlcPlaybackSurface.tsx"),/VLC_BUFFERING/); assert.match(source("components/player/VlcPlaybackSurface.tsx"),/VLC_ERROR/);
console.log("R18-C2 credential-safe trace scenarios passed.");
